{
  description = "Example target-system config for use with ezconf";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Included so the installed system can keep running ezconf itself (e.g.
    # `services.ezconf.enable = true;` from a JSON tab) for future
    # reconfiguration, not just during the live-ISO install.
    ezconf.url = "github:kalken/ezconf/develop";
    ezconf.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, ezconf }:
    let
      system = "x86_64-linux";
    in
    {
      # Rename "myhost" to taste - ezinstall picks whichever
      # nixosConfigurations attrs exist here (asking if there's more than
      # one) and installs that one.
      nixosConfigurations.myhost = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          # Generated by the "Hardware config" buttons.
          ./hardware-configuration.nix
          # ezconf's own configDir (its default: /etc/nixos/ezconf) - a
          # directory module, auto-imported via its default.nix, that merges
          # whatever *.json tabs you edit in the ezconf UI.
          ./ezconf

          ezconf.nixosModules.default

          { system.stateVersion = "26.11"; }
        ];
      };
    };
}
